# Generated by Django 4.2.11 on 2024-05-18 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, max_length=130, null=True, verbose_name='age')),
                ('gender', models.TextField(blank=True, choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], null=True, verbose_name='gender')),
                ('profile_pic', models.ImageField(default='profile_pic.png', upload_to='profile_pics', verbose_name='profile picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
