# Generated by Django 4.2.11 on 2024-05-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_pic.jpg', upload_to='profile_pics', verbose_name='profile picture'),
        ),
    ]
