# Generated by Django 4.2.11 on 2024-05-02 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='What is your post about?', max_length=300, unique=True, verbose_name='title')),
                ('category', models.CharField(choices=[('producto', 'Producto'), ('empresa', 'Empresa'), ('música', 'Música'), ('pelicula', 'Pelicula'), ('famoso', 'Famoso'), ('vida', 'Vida')], default='vida', help_text='what category is it?', max_length=8, verbose_name='category')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='when this post was created', verbose_name='date')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the name of the tag', max_length=20, verbose_name='name')),
                ('posts', models.ManyToManyField(to='main.post')),
            ],
        ),
    ]
